development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:8c976500a1108543316beac1f9aaf54b@spinyfin.redistogo.com:11545/
  channel_prefix: type-battles-v2-backend_production
